### ISSUE TITLE
Include more tests

### ISSUE THREAD

**Issue by nymann** [nymann/fastapi-code-generator#2]
The tests structure should look like this

```
tests
├── conftest.py
├── __init__.py
├── test_{{ ROUTE }}
│   ├── __init__.py
│   ├── test_basic_positive.py
│   ├── test_destructive.py
│   ├── test_extended_positive.py
│   ├── test_invalid_input_negative.py
│   └── test_valid_input_negative.py
└── utils.py
```

https://www.sisense.com/blog/rest-api-testing-strategy-what-exactly-should-you-test/

An example of `test_basic_positive.py` can be found at https://github.com/chessdb/api/blob/master/tests/test_positions/test_basic_positive.py

**Comment by sebastian-kjaersgaard** [comment]
Issue fixed in newest version
